# Generated by Django 4.2.25 on 2026-02-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='whatsapp_business_number',
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='whatsapp_access_token',
            field=models.CharField(blank=True, help_text='Permanent access token from Meta', max_length=500),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='whatsapp_business_account_id',
            field=models.CharField(blank=True, help_text='WhatsApp Business Account ID (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, help_text='Phone Number ID from Meta Developer Console', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsappnotification',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
