# Generated by Django 4.2.27 on 2026-01-13 15:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_add_idempotency_and_status_lifecycle'),
        ('inventory', '0002_add_barcode_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, help_text='Sequential invoice number (e.g., TRAP/INV/2026/0001)', max_length=50, unique=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, help_text='Sum of all line items (before discount)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_type', models.CharField(choices=[('NONE', 'No Discount'), ('PERCENTAGE', 'Percentage Discount'), ('FLAT', 'Flat Discount')], default='NONE', max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (0-100) or flat amount', max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated discount amount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final payable amount (subtotal - discount)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('billing_name', models.CharField(max_length=200)),
                ('billing_phone', models.CharField(max_length=20)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('pdf_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.sale')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='TRAP/INV', max_length=20)),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('prefix', 'year')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=300)),
                ('variant_details', models.CharField(blank=True, help_text="Size/color snapshot (e.g., 'M / Blue')", max_length=100)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of sale', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='quantity × unit_price', max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='invoices.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_in_invoice_e6b546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoices_in_invoice_087f87_idx'),
        ),
    ]
