# Generated by Django 4.2.25 on 2026-01-15 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(default='TRAP INVENTORY', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Premium Apparel', max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number (optional)', max_length=20)),
                ('footer_text', models.TextField(blank=True, default='Thank you for shopping with us!')),
                ('terms_text', models.TextField(blank=True, default='All items are non-refundable. Exchange within 7 days with receipt.')),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
            },
        ),
    ]
