# Generated by Django 4.2.27 on 2026-01-16 07:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_add_business_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='admin_max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Maximum discount percentage ADMIN can apply', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='available_discounts',
            field=models.JSONField(blank=True, default=list, help_text="List of preset discounts: [{type: 'PERCENTAGE'|'FLAT', value: number, label: string}]"),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='discount_enabled',
            field=models.BooleanField(default=True, help_text='Whether discounts can be applied at POS'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='staff_max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Maximum discount percentage STAFF can apply', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
