# Generated by Django 4.2.25 on 2026-01-18 21:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_add_discount_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['id'], 'verbose_name': 'Invoice Item', 'verbose_name_plural': 'Invoice Items'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_gstin',
            field=models.CharField(blank=True, help_text='Customer GSTIN (optional)', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total GST amount (sum of all line GST)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST amount for this line (snapshotted)', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST percentage at time of sale (snapshotted)', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='line_total_with_gst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final line amount including GST', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sku',
            field=models.CharField(blank=True, help_text='Product SKU snapshot', max_length=100),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount after pro-rata discount, before GST', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Final payable amount (subtotal - discount + GST)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, help_text='quantity × unit_price (before discount/GST)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price at time of sale (exclusive of GST)', max_digits=10),
        ),
    ]
