# Generated by Django 4.2.27 on 2026-01-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Unique barcode for POS scanning. Auto-generated on creation.', max_length=50, null=True, unique=True),
        ),
    ]
