# Generated by Django 4.2.25 on 2026-01-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_barcode_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MENS', "Men's"), ('WOMENS', "Women's"), ('UNISEX', 'Unisex'), ('KIDS', 'Kids')], default='UNISEX', help_text='Target gender for the product', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='Primary material/fabric (e.g., 100% Cotton, Cotton/Polyester Blend)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, help_text='Season collection (e.g., SS24, FW23)', max_length=50),
        ),
    ]
