# Generated by Django 4.2 - Phase 10A Product Master Upgrade
# This migration is NON-DESTRUCTIVE and handles:
# 1. New fields on Product model
# 2. ProductPricing and ProductImage models
# 3. Backfill existing products with SKU/barcode

from django.db import migrations, models
import uuid
import django.core.validators
from decimal import Decimal


def generate_sku(name, brand):
    """Generate a unique SKU based on product name and brand."""
    import time
    import random
    
    brand_code = ''.join(c for c in brand.upper() if c.isalnum())[:3] or "GEN"
    name_clean = ''.join(c for c in name.upper() if c.isalnum())
    name_code = name_clean[:5] if len(name_clean) >= 5 else name_clean.ljust(5, 'X')
    random_suffix = ''.join(random.choices('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', k=4))
    
    return f"{brand_code}-{name_code}-{random_suffix}"


def generate_barcode():
    """Generate a unique barcode value."""
    import time
    import random
    
    timestamp_part = str(int(time.time()))[-6:]
    random_part = ''.join(random.choices('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', k=5))
    
    return f"TRAP-{timestamp_part}-{random_part}"


def backfill_sku_and_barcode(apps, schema_editor):
    """
    Backfill existing products with auto-generated SKU and barcode.
    This is run during migration to ensure all products have these fields.
    """
    Product = apps.get_model('inventory', 'Product')
    
    for product in Product.objects.filter(sku__isnull=True):
        sku = generate_sku(product.name, product.brand)
        # Ensure uniqueness
        counter = 1
        original_sku = sku
        while Product.objects.filter(sku=sku).exclude(pk=product.pk).exists():
            sku = f"{original_sku}-{counter}"
            counter += 1
        product.sku = sku
        product.save(update_fields=['sku'])
    
    for product in Product.objects.filter(barcode_value__isnull=True):
        barcode = generate_barcode()
        # Ensure uniqueness
        while Product.objects.filter(barcode_value=barcode).exclude(pk=product.pk).exists():
            barcode = generate_barcode()
        product.barcode_value = barcode
        product.save(update_fields=['barcode_value'])


def set_is_deleted_default(apps, schema_editor):
    """Set is_deleted = False for all existing products."""
    Product = apps.get_model('inventory', 'Product')
    Product.objects.filter(is_deleted__isnull=True).update(is_deleted=False)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_apparel_fields'),
    ]

    operations = [
        # Add new fields to Product model
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Unique product SKU (auto-generated if not provided)',
                max_length=100,
                null=True,
                unique=True
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_value',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Code128 barcode value (auto-generated, immutable)',
                max_length=128,
                null=True,
                unique=True
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_image_url',
            field=models.TextField(
                blank=True,
                help_text='URL to barcode SVG image',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text='Optional reference to Brand entity',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text='Optional reference to Category entity',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Flexible attributes: sizes, colors, pattern, fit, material, season, etc.'
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Soft delete flag. Deleted products hidden from POS, visible in admin.'
            ),
        ),
        
        # Alter existing fields to match Phase 10A spec
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[
                    ('MENS', "Men's"),
                    ('WOMENS', "Women's"),
                    ('UNISEX', 'Unisex'),
                    ('KIDS', 'Kids')
                ],
                default='UNISEX',
                help_text='Target gender for the product',
                max_length=50,
                null=True
            ),
        ),
        
        # Add indexes
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_p_is_acti_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'category'], name='inventory_p_brand_idx'),
        ),
        
        # Create ProductPricing model
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False
                )),
                ('cost_price', models.DecimalField(
                    decimal_places=2,
                    help_text='Cost price / purchase price',
                    max_digits=10,
                    validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]
                )),
                ('mrp', models.DecimalField(
                    decimal_places=2,
                    help_text='Maximum Retail Price',
                    max_digits=10,
                    validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]
                )),
                ('selling_price', models.DecimalField(
                    decimal_places=2,
                    help_text='Actual selling price',
                    max_digits=10,
                    validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]
                )),
                ('gst_percentage', models.DecimalField(
                    decimal_places=2,
                    default=Decimal('0.00'),
                    help_text='GST percentage (e.g., 5.00, 12.00, 18.00)',
                    max_digits=5,
                    validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='pricing',
                    to='inventory.product'
                )),
            ],
            options={
                'verbose_name': 'Product Pricing',
                'verbose_name_plural': 'Product Pricing',
            },
        ),
        
        # Create ProductImage model
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False
                )),
                ('image_url', models.TextField(help_text='URL to the product image')),
                ('is_primary', models.BooleanField(
                    default=False,
                    help_text='Is this the primary/main product image?'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='images',
                    to='inventory.product'
                )),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        
        # Backfill existing products with SKU and barcode
        migrations.RunPython(backfill_sku_and_barcode, migrations.RunPython.noop),
        migrations.RunPython(set_is_deleted_default, migrations.RunPython.noop),
    ]
