# Generated by Django 4.2 - Phase 10.1 SKU Sequence
# This migration creates the SKUSequence model for deterministic SKU generation
# and backfills sequence counters from existing products.

from django.db import migrations, models
import uuid
import re


def parse_sku_sequence(sku: str) -> int:
    """
    Try to parse sequence number from existing SKU.
    Returns 0 if parsing fails.
    """
    if not sku:
        return 0
    
    # Try to match format: BRAND-CATEGORY-NNNNNN
    match = re.search(r'-(\d{6})$', sku)
    if match:
        return int(match.group(1))
    
    # Try to match format: XXX-XXXXX-XXXX (old random format) - return 0
    return 0


def backfill_sku_sequences(apps, schema_editor):
    """
    Backfill SKUSequence counters from existing products.
    
    For each unique brand+category combination, find the max sequence number
    used and set the counter accordingly.
    
    This ensures new products get higher sequence numbers than existing ones.
    """
    Product = apps.get_model('inventory', 'Product')
    SKUSequence = apps.get_model('inventory', 'SKUSequence')
    
    # Get all unique brand+category combinations
    combinations = Product.objects.values('brand', 'category').distinct()
    
    for combo in combinations:
        brand = combo['brand'].upper().strip()[:100] if combo['brand'] else ''
        category = combo['category'].upper().strip()[:100] if combo['category'] else ''
        
        if not brand or not category:
            continue
        
        # Find max sequence number for this combination
        max_seq = 0
        products = Product.objects.filter(
            brand__iexact=brand,
            category__iexact=category
        )
        
        for product in products:
            seq = parse_sku_sequence(product.sku)
            if seq > max_seq:
                max_seq = seq
        
        # Create or update sequence counter
        SKUSequence.objects.update_or_create(
            brand=brand,
            category=category,
            defaults={'last_sequence': max_seq}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_master_upgrade'),
    ]

    operations = [
        # Create SKUSequence table
        migrations.CreateModel(
            name='SKUSequence',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False
                )),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SKU Sequence',
                'verbose_name_plural': 'SKU Sequences',
                'unique_together': {('brand', 'category')},
            },
        ),
        
        # Backfill sequence counters from existing products
        migrations.RunPython(backfill_sku_sequences, migrations.RunPython.noop),
    ]
