# Generated by Django 4.2.25 on 2026-01-17 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_sku_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warehouse_id', models.UUIDField(blank=True, help_text='Warehouse UUID (Phase 12 will normalize)', null=True)),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening Stock'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damage'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out')], db_index=True, max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('reference_type', models.CharField(blank=True, help_text="Type of reference document (e.g., 'purchase_order', 'sale', 'adjustment')", max_length=50)),
                ('reference_id', models.UUIDField(blank=True, help_text='UUID of the reference document', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes about this movement')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_is_acti_d704d0_idx',
            old_name='inventory_p_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_brand_81a099_idx',
            old_name='inventory_p_brand_idx',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this movement', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(help_text='Product this movement applies to', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product'], name='inventory_i_product_2153f2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type'], name='inventory_i_movemen_e5f549_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['created_at'], name='inventory_i_created_75a91c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', 'warehouse_id'], name='inventory_i_product_e24d47_idx'),
        ),
    ]
