# Generated by Django 4.2.25 on 2026-01-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_movement'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_product_e24d47_idx',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='warehouse_id',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse for this movement (required for OPENING, PURCHASE, SALE, TRANSFER)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_i_product_e24d47_idx'),
        ),
    ]
