# Generated by Django 4.2.27 on 2026-01-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_stores_and_transfers'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_product_store_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='inventory_s_transfe_639a89_idx',
            old_name='inventory_s_transfe_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='inventory_s_status_8e22d4_idx',
            old_name='inventory_s_status_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='inventory_s_source__f02fcd_idx',
            old_name='inventory_s_source__j1k2l3_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='inventory_s_destina_38842b_idx',
            old_name='inventory_s_destin_m4n5o6_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='inventory_s_transfe_b40a2a_idx',
            old_name='inventory_s_transfe_p7q8r9_idx',
        ),
        migrations.RenameIndex(
            model_name='store',
            new_name='inventory_s_code_a4e733_idx',
            old_name='inventory_s_code_8a8c3d_idx',
        ),
        migrations.RenameIndex(
            model_name='store',
            new_name='inventory_s_city_73e89e_idx',
            old_name='inventory_s_city_9c1e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='store',
            new_name='inventory_s_is_acti_338125_idx',
            old_name='inventory_s_is_acti_a2b3c5_idx',
        ),
    ]
