# Generated by Django 4.2.27 on 2026-01-29 23:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0007_add_credit_payment_support'),
        ('inventory', '0011_remove_inventorymovement_inventory_i_product_store_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(help_text='Credit note number: CR-YYYY-NNNNNN', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('return_reason', models.CharField(choices=[('DEFECTIVE', 'Defective Product'), ('WRONG_ITEM', 'Wrong Item Delivered'), ('SIZE_ISSUE', 'Size Issue'), ('COLOR_ISSUE', 'Color Issue'), ('CUSTOMER_DISSATISFACTION', 'Customer Dissatisfaction'), ('DAMAGE_IN_TRANSIT', 'Damage in Transit'), ('EXPIRED', 'Expired Product'), ('OTHER', 'Other')], help_text='Primary reason for return', max_length=30)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about the return')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total refund amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual amount refunded to customer', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('return_date', models.DateField(help_text='Date customer returned the items')),
                ('issue_date', models.DateField(blank=True, help_text='Date credit note was issued', null=True)),
                ('settlement_date', models.DateField(blank=True, help_text='Date customer was refunded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes_created', to=settings.AUTH_USER_MODEL)),
                ('original_sale', models.ForeignKey(help_text='Original sale transaction', on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.sale')),
                ('warehouse', models.ForeignKey(help_text='Warehouse where stock is returned', on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Credit Note',
                'verbose_name_plural': 'Credit Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Credit Note Sequence',
                'verbose_name_plural': 'Credit Note Sequences',
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit_note_number', models.CharField(help_text='Debit note number: DR-YYYY-NNNNNN', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('ACCEPTED', 'Accepted by Supplier'), ('SETTLED', 'Settled'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('return_reason', models.CharField(choices=[('DEFECTIVE_RECEIVED', 'Defective Items Received'), ('WRONG_ITEMS', 'Wrong Items Delivered'), ('EXCESS_STOCK', 'Excess Stock'), ('EXPIRED', 'Expired Products'), ('DAMAGE_IN_TRANSIT', 'Damage in Transit'), ('QUALITY_ISSUES', 'Quality Issues'), ('ORDER_CANCELLATION', 'Order Cancellation'), ('OTHER', 'Other')], help_text='Primary reason for return', max_length=30)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about the return')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total return amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount adjusted by supplier', max_digits=12)),
                ('return_date', models.DateField(help_text='Date items were returned to supplier')),
                ('issue_date', models.DateField(blank=True, help_text='Date debit note was issued', null=True)),
                ('settlement_date', models.DateField(blank=True, help_text='Date supplier settled the return', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes_created', to=settings.AUTH_USER_MODEL)),
                ('original_purchase_order', models.ForeignKey(help_text='Original purchase order', on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='inventory.purchaseorder')),
                ('supplier', models.ForeignKey(help_text='Supplier to return items to', on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='inventory.supplier')),
                ('warehouse', models.ForeignKey(help_text='Warehouse from which stock is returned', on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Debit Note',
                'verbose_name_plural': 'Debit Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebitNoteSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Debit Note Sequence',
                'verbose_name_plural': 'Debit Note Sequences',
            },
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING', 'Opening Stock'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('RETURN_INWARD', 'Return Inward (Customer Return)'), ('RETURN_OUTWARD', 'Return Outward (Supplier Return)'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damage'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='DebitNoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_returned', models.PositiveIntegerField(help_text='Quantity being returned', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Original unit price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total for this line (calculated)', max_digits=12)),
                ('condition', models.CharField(choices=[('GOOD', 'Good Condition'), ('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective'), ('EXPIRED', 'Expired')], default='GOOD', help_text='Condition of returned item', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.debitnote')),
                ('original_purchase_order_item', models.ForeignKey(help_text='Original purchase order item being returned', on_delete=django.db.models.deletion.PROTECT, related_name='debit_note_items', to='inventory.purchaseorderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_note_items', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Debit Note Item',
                'verbose_name_plural': 'Debit Note Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_returned', models.PositiveIntegerField(help_text='Quantity being returned', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Original unit price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total for this line (calculated)', max_digits=12)),
                ('condition', models.CharField(choices=[('GOOD', 'Good Condition'), ('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective'), ('EXPIRED', 'Expired')], default='GOOD', help_text='Condition of returned item', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.creditnote')),
                ('original_sale_item', models.ForeignKey(help_text='Original sale item being returned', on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_items', to='sales.saleitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_items', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Credit Note Item',
                'verbose_name_plural': 'Credit Note Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='debitnote',
            index=models.Index(fields=['debit_note_number'], name='inventory_d_debit_n_8b0e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='debitnote',
            index=models.Index(fields=['status'], name='inventory_d_status_2aebf2_idx'),
        ),
        migrations.AddIndex(
            model_name='debitnote',
            index=models.Index(fields=['return_date'], name='inventory_d_return__1d78d6_idx'),
        ),
        migrations.AddIndex(
            model_name='debitnote',
            index=models.Index(fields=['original_purchase_order'], name='inventory_d_origina_2b95ea_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['credit_note_number'], name='inventory_c_credit__0a3654_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['status'], name='inventory_c_status_5d5493_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['return_date'], name='inventory_c_return__4e5e35_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['original_sale'], name='inventory_c_origina_f3f5c8_idx'),
        ),
    ]
