# Generated by Django 4.2.27 on 2026-01-13 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Reason for FAILED status', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='idempotency_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Client-provided key to prevent duplicate checkouts', unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['idempotency_key'], name='sales_sale_idempot_e1608d_idx'),
        ),
    ]
