# Generated by Django 4.2.25 on 2026-01-18 20:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_phase12_warehouse_normalization'),
        ('sales', '0003_phase13_pos_engine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['id'], 'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Items'},
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_sale_nu_99d8fe_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_invoice_78d822_idx',
            old_name='sales_sale_invoice_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_warehou_2a26f7_idx',
            old_name='sales_sale_wh_created_idx',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='variant',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('PERCENT', 'Percent'), ('FLAT', 'Flat')], help_text='PERCENT or FLAT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount or percentage', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Sum of all line totals before discount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Final total after discount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_items',
            field=models.PositiveIntegerField(default=0, help_text='Total quantity of items sold'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(help_text='Product sold (Phase 13: product-level, not variant)', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity sold', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Price at time of sale (snapshotted)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
