# Generated by Django 4.2.25 on 2026-01-18 20:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_phase13_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_gst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total GST amount for the sale (sum of all line GST)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST amount: calculated on discounted line amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST percentage applied (0-100, locked at sale time)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='line_total_with_gst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final line total including GST', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Final total after discount and GST', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, help_text='quantity × selling_price (before GST)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Price at time of sale (snapshotted, exclusive of GST)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
