# Generated by Django 4.2.25 on 2026-01-18 21:27

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_phase12_warehouse_normalization'),
        ('sales', '0005_phase13_1_gst_hardening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason for return')),
                ('refund_subtotal', models.DecimalField(decimal_places=2, help_text='Refund subtotal (before GST)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('refund_gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Refund GST amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Total refund amount (subtotal + GST)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns_created', to=settings.AUTH_USER_MODEL)),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity being returned', validators=[django.core.validators.MinValueValidator(1)])),
                ('line_refund', models.DecimalField(decimal_places=2, help_text='Line refund (based on original price)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst_refund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST refund for this line', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('return_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.return')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.saleitem')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['original_sale'], name='sales_retur_origina_24edba_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['created_at'], name='sales_retur_created_375cdb_idx'),
        ),
    ]
