# Generated by Django 4.2.25 on 2026-01-29 19:56

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0006_phase15_returns'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid towards credit balance', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('CREDIT', 'Credit (Pay Later)')], help_text='Payment method used', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Credit Payment',
                'verbose_name_plural': 'Credit Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original credit amount (pay later portion)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='sale',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining balance due from customer', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='sale',
            name='credit_status',
            field=models.CharField(choices=[('NONE', 'No Credit'), ('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid')], default='NONE', help_text='Current status of credit payment', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_address',
            field=models.TextField(blank=True, default='', help_text='Customer address for delivery/billing'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_email',
            field=models.EmailField(blank=True, default='', help_text='Customer email for marketing', max_length=254),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_mobile',
            field=models.CharField(blank=True, default='', help_text='Customer mobile number for marketing', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_credit_sale',
            field=models.BooleanField(default=False, help_text='Whether this sale includes a credit/pay-later component'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('CREDIT', 'Credit (Pay Later)')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_credit_sale', 'credit_status'], name='sales_sale_is_cred_08c15b_idx'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='received_by',
            field=models.ForeignKey(help_text='User who received this payment', on_delete=django.db.models.deletion.PROTECT, related_name='credit_payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='sale',
            field=models.ForeignKey(help_text='The credit sale this payment is against', on_delete=django.db.models.deletion.PROTECT, related_name='credit_payments', to='sales.sale'),
        ),
    ]
