# Generated by Django 4.2.25 on 2026-02-01 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_supplier_barcode_tracking'),
        ('sales', '0007_add_credit_payment_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier of this product (snapshotted at sale time)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='inventory.supplier'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['supplier'], name='sales_salei_supplie_8a41aa_idx'),
        ),
    ]
